export default {
  "menu": [{
    "id": 1,
    "num": "001",
    "name": "Cafe americano",
    "img": "http://www.serebii.net/pokemongo/pokemon/001.png",
    "type": "breakfast",
    "price": "$5",
  },{
    "id": 2,
    "num": "002",
    "name": "Cafe con leche",
    "img": "http://www.serebii.net/pokemongo/pokemon/001.png",
    "type": "breakfast",
    "price": "$7",
  },{
    "id": 3,
    "num": "003",
    "name": "Sandwich de J y Q",
    "img": "http://www.serebii.net/pokemongo/pokemon/001.png",
    "type": "breakfast",
    "price": "$10",
  },{
    "id": 4,
    "num": "004",
    "name": "Jugo de frutas",
    "img": "http://www.serebii.net/pokemongo/pokemon/001.png",
    "type": "breakfast",
    "price": "$7",
  },{
    "id": 5,
    "num": "005",
    "name": "Burger simple",
    "img": "http://www.serebii.net/pokemongo/pokemon/001.png",
    "type": "launch",
    "price": "$10",
  },{
    "id": 6,
    "num": "006",
    "name": "Burger doble",
    "img": "http://www.serebii.net/pokemongo/pokemon/001.png",
    "type": "launch",
    "price": "$15",
  },{
    "id": 7,
    "num": "007",
    "name": "Aros de cebeolla",
    "img": "http://www.serebii.net/pokemongo/pokemon/001.png",
    "type": "launch",
    "price": "$5",
  },{
    "id": 8,
    "num": "008",
    "name": "Papas fritas",
    "img": "http://www.serebii.net/pokemongo/pokemon/001.png",
    "type": "launch",
    "price": "$5",
  },{
    "id": 9,
    "num": "009",
    "name": "Agua 500ml",
    "img": "http://www.serebii.net/pokemongo/pokemon/001.png",
    "type": "drinks",
    "price": "$5",
  },{
    "id": 10,
    "num": "010",
    "name": "Agua 750ml",
    "img": "http://www.serebii.net/pokemongo/pokemon/001.png",
    "type": "drinks",
    "price": "$7",
  },{
    "id": 11,
    "num": "011",
    "name": "Bebida 500ml",
    "img": "http://www.serebii.net/pokemongo/pokemon/001.png",
    "type": "drinks",
    "price": "$7",
  },{
    "id": 12,
    "num": "012",
    "name": "Bebida 750ml",
    "img": "http://www.serebii.net/pokemongo/pokemon/001.png",
    "type": "drinks",
    "price": "$10",
  }
]}
