export default {
  menu: [
    {
      id: 1,
      num: "001",
      name: "Cafe americano",
      img: "https://i.ibb.co/fHWzXCS/icon-cafeamericano.png",
      type: "breakfast",
      price: 5,
      quantity: 1,
    },
    {
      id: 2,
      num: "002",
      name: "Cafe con leche",
      img: "https://i.ibb.co/HDYmsvD/icon-cafeconleche.png",
      type: "breakfast",
      price: 7,
      quantity: 1,
    },
    {
      id: 3,
      num: "003",
      name: "Sandwich de J y Q",
      img: "https://i.ibb.co/5GFKWX8/icon-sandwich.png",
      type: "breakfast",
      price: 10,
      quantity: 1,
    },
    {
      id: 4,
      num: "004",
      name: "Jugo de frutas",
      img: "https://i.ibb.co/pnLpQDT/icon-jugodefrutas.png",
      type: "breakfast",
      price: 7,
      quantity: 1,
    },
    {
      id: 5,
      num: "005",
      name: "Burger simple",
      img: "https://i.ibb.co/bRPjC6N/icon-burguersimple.png",
      type: "launch",
      price: 10,
      quantity: 1,
    },
    {
      id: 6,
      num: "006",
      name: "Burger doble",
      img: "https://i.ibb.co/xY4GNvZ/icon-burguerdoble.png",
      type: "launch",
      price: 15,
      quantity: 1,
    },
    {
      id: 7,
      num: "007",
      name: "Aros de cebolla",
      img: "https://i.ibb.co/2PWFXM7/icon-onionrings.png",
      type: "launch",
      price: 5,
      quantity: 1,
    },
    {
      id: 8,
      num: "008",
      name: "Papas fritas",
      img: "https://i.ibb.co/gt0XwHz/icon-papasfritas.png",
      type: "launch",
      price: 5,
      quantity: 1,
    },
    {
      id: 9,
      num: "009",
      name: "Agua 500ml",
      img: "https://i.ibb.co/LzxvRxk/icon-water.png",
      type: "drinks",
      price: 5,
      quantity: 1,
    },
    {
      id: 10,
      num: "010",
      name: "Agua 750ml",
      img: "https://i.ibb.co/68CYDVh/icon-water750ml.png",
      type: "drinks",
      price: 7,
      quantity: 1,
    },
    {
      id: 11,
      num: "011",
      name: "Bebida 500ml",
      img: "https://i.ibb.co/L6sbPMt/icon-soda500ml.png",
      type: "drinks",
      price: 7,
      quantity: 1,
    },
    {
      id: 12,
      num: "012",
      name: "Bebida 750ml",
      img: "https://i.ibb.co/sjmsZgs/icon-soda750ml.png",
      type: "drinks",
      price: 10,
      quantity: 1,
    },
  ],
};
